name: CD
on:
  push:
    paths:
      - patches.flp
      - Plugin_FLEP.zip
  workflow_run:
    workflows:
      - CI
    types:
      - completed
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          zip patches.zip patches.flp patches.dll Plugin_FLEP.zip
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add patches.zip
          git commit -m "Update patches.zip"
          git push
