name: CI/CD
on:
  push:
    paths:
      - source/**
      - patches.flp
      - Plugin_FLEP/**
concurrency:
  group: CI/CD
  cancel-in-progress: true
jobs:
  update:
    needs: forward
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          [System.IO.Directory]::SetCurrentDirectory($pwd)
          Add-Type -TypeDefinition @'
          using System;
          using System.Runtime.InteropServices;

          namespace Application {
              public static class Platform {
                  [DllImport("kernel32.dll", CharSet = CharSet.Unicode, SetLastError = true)]
                  public static extern IntPtr BeginUpdateResource(string pFileName, bool bDeleteExistingResources);

                  [DllImport("kernel32.dll", CharSet = CharSet.Unicode, SetLastError = true)]
                  public static extern bool UpdateResource(IntPtr hUpdate, IntPtr lpType, string lpName, ushort wLanguage, byte[] lpData, uint cb);

                  [DllImport("kernel32.dll", CharSet = CharSet.Unicode, SetLastError = true)]
                  public static extern bool EndUpdateResource(IntPtr hUpdate, bool fDiscard);
              }
          }
          '@
          $module = [Application.Platform]::BeginUpdateResource('patches.dll', $false)
          $type = New-Object -TypeName IntPtr -ArgumentList 10
          $data = [System.IO.File]::ReadAllBytes('source\patches.c') + (New-Object -TypeName byte[] -ArgumentList 1)
          [Application.Platform]::UpdateResource($module, $type, 'patches.c', 1033, $data, $data.Length)
          [Application.Platform]::EndUpdateResource($module, $false)
          Compress-Archive -Path Plugin_FLEP\* -DestinationPath Plugin_FLEP.zip -Update
          Compress-Archive -Path patches.dll, patches.flp, Plugin_FLEP.zip, source -DestinationPath patches.zip -Update
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add patches.dll patches.zip Plugin_FLEP.zip
          git commit -m 'Update patches'
          git push
  forward:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: flep
      - uses: actions/checkout@v4
        with:
          repository: FlexiblePatcher/FlexiblePatcher
          token: ${{ secrets.OAT }}
          path: FlexiblePatcher
      - uses: actions/checkout@v4
        with:
          repository: FlexiblePatcher/tools
          path: tools
      - run: |
          py tools\convert.py flep\patches.flp FlexiblePatcher\patches.flp
          Remove-Item -Path FlexiblePatcher\source -Recurse
          Copy-Item -Path flep\source -Destination FlexiblePatcher -Recurse
          Move-Item -Path FlexiblePatcher\source\patches.c -Destination FlexiblePatcher\Plugin_FlexiblePatcher\source\plugin_patcher\patches.cpp
          Copy-Item -Path flep\Plugin_FLEP\Plugin_FLEP.txt -Destination FlexiblePatcher\Plugin_FlexiblePatcher\Plugin_FlexiblePatcher.txt
          Copy-Item -Path flep\Plugin_FLEP\Plugin_FLEP.script -Destination FlexiblePatcher\Plugin_FlexiblePatcher\Plugin_FlexiblePatcher.script
          Remove-Item -Path FlexiblePatcher\Plugin_FlexiblePatcher\Manual -Recurse
          Copy-Item -Path flep\Plugin_FLEP\Manual -Destination FlexiblePatcher\Plugin_FlexiblePatcher -Recurse
          py tools\rename.py FlexiblePatcher\patches.flp FlexiblePatcher\Plugin_FlexiblePatcher\Plugin_FlexiblePatcher.txt FlexiblePatcher\Plugin_FlexiblePatcher\Manual\Manual.html
          $message = git -C flep show -s --format=%B | Out-String
          git -C FlexiblePatcher config user.name github-actions[bot]
          git -C FlexiblePatcher config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git -C FlexiblePatcher add -A
          git -C FlexiblePatcher commit -m $message
          git -C FlexiblePatcher push
